# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Palbase < Formula
  desc "Palbase CLI — develop, test, and deploy backend projects"
  homepage "https://palbase.studio"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.2/palbase_darwin_amd64.tar.gz"
      sha256 "8abff047effe9e3fb7e30f46c09090d1f3424b4ec51571671edb941b87444c51"

      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.2/palbase_darwin_arm64.tar.gz"
      sha256 "4ed0774a3b7eb8dc3fe2b7ce5c65c7e4db534347e4fdc3a3e6045dfec2180768"

      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.2/palbase_linux_amd64.tar.gz"
      sha256 "78b331d11e182f9c132351143c587201665ef5155d8078ed7c79a279e9854b03"
      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.2.2/palbase_linux_arm64.tar.gz"
      sha256 "4659efa64d37226a9be7583564d4753b323392e286026d53fec65990a5ed6528"
      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  test do
    system "#{bin}/palbase", "--version"
  end
end
