# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Palbase < Formula
  desc "Palbase CLI — develop backend code and deploy it to environments"
  homepage "https://palbase.studio"
  version "0.42.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.42.0/palbase_darwin_amd64.tar.gz"
      sha256 "a6661603b17c8aa5bbcd4caf6bf0ff35132baa4d67ea6a09a824657736033087"

      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.42.0/palbase_darwin_arm64.tar.gz"
      sha256 "db5be8f44fdbed22466d601cd5325b9e76de970c647cbbe2030e9d40808ef55e"

      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.42.0/palbase_linux_amd64.tar.gz"
      sha256 "faf71910851370e50e82c37ee6d23a3c72a7f4f55c181435bc36d9d82313b07d"
      define_method(:install) do
        bin.install "palbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/palgroup/palbase-cli/releases/download/v0.42.0/palbase_linux_arm64.tar.gz"
      sha256 "66407b3281caefbb89db5a8f7a4dd21e39b393f96fbbf3e2208bfbd95bd462a6"
      define_method(:install) do
        bin.install "palbase"
      end
    end
  end

  test do
    system "#{bin}/palbase", "--version"
  end
end
